name = "FastIsostasy"
uuid = "80efc11e-3694-4407-a4bf-24e5955cde3d"
authors = ["Jan Swierczek-Jereczek"]
version = "1.0.0"

[deps]
AbstractFFTs = "621f4979-c628-5d54-868e-fcf4e3e8185c"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
FiniteDifferences = "26cc04aa-876d-5657-8c51-4c34ba976000"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[weakdeps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EnsembleKalmanProcesses = "aa8a2aa5-91d8-4396-bcef-d4f2ec43552d"

[extensions]
FastIsostasyEnsembleKalmanProcessesExt = ["EnsembleKalmanProcesses", "Distributions"]

[compat]
AbstractFFTs = "1.5"
CUDA = "5"
DelimitedFiles = "1.9"
Distributions = "0.25"
Downloads = "1.6"
EnsembleKalmanProcesses = "2.0"
FFTW = "1.8"
FastGaussQuadrature = "1.0"
FiniteDifferences = "0.12.32"
Interpolations = "0.14, 0.15"
NetCDF = "0.11, 0.12"
OrdinaryDiffEqLowOrderRK = "1.2.0"
OrdinaryDiffEqTsit5 = "1.1"
ParallelStencil = "0.13"
Proj = "1.7"
Reexport = "1"
SpecialFunctions = "2.4"
Statistics = "1.9"
julia = "1.9"
